GOOS=darwin GOARCH=amd64 go build -o ./pkg/wrapper-darwin-amd64 ./cmd/wrapper/main.go
GOOS=darwin GOARCH=arm64 go build -o ./pkg/wrapper-darwin-arm64 ./cmd/wrapper/main.go
GOOS=linux GOARCH=386 go build -o ./pkg/wrapper-linux-386 ./cmd/wrapper/main.go
GOOS=linux GOARCH=amd64 go build -o ./pkg/wrapper-linux-amd64 ./cmd/wrapper/main.go
GOOS=linux GOARCH=arm go build -o ./pkg/wrapper-linux-arm ./cmd/wrapper/main.go
GOOS=linux GOARCH=arm64 go build -o ./pkg/wrapper-linux-arm64 ./cmd/wrapper/main.go
GOOS=windows GOARCH=386 go build -o ./pkg/wrapper-windows-386.exe ./cmd/wrapper/main.go
GOOS=windows GOARCH=amd64 go build -o ./pkg/wrapper-windows-amd64.exe ./cmd/wrapper/main.go
GOOS=windows GOARCH=arm go build -o ./pkg/wrapper-windows-arm.exe ./cmd/wrapper/main.go
GOOS=windows GOARCH=arm64 go build -o ./pkg/wrapper-windows-arm64.exe ./cmd/wrapper/main.go
