name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [386, amd64, arm, arm64]
        exclude:
          # excludes 386 and arm on darwin
          - os: darwin
            arch: 386
          - os: darwin
            arch: arm
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: |
            go get github.com/maja42/ember/
      - name: Build
        run: |
            ./scripts/build.sh
      - name: Generate Artifacts
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: exwrap-${{ matrix.os }}-${{ matrix.arch }}.zip
          path: ${{github.workspace}}/build/${{ matrix.os }}/${{ matrix.arch }}
