name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [386, amd64, arm, arm64]
        exclude:
          # excludes 386 and arm on darwin
          - os: darwin
            arch: 386
          - os: darwin
            arch: arm
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: |
            go get github.com/maja42/ember/
      - name: Build
        run: |
            ./scripts/build.sh
            zip -r9 --symlinks app.zip ${{github.workspace}}/build/${{ matrix.os }}/${{ matrix.arch }}
      - name: Generate Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.zip
      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app.zip
          asset_name: exwrap-${{ github.event.release.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_content_type: application/zip
